FROM brainlife/mcr:r2019a

LABEL author=fn

ENV LANG=C.UTF-8

# 设置使用阿里云的镜像源
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list \
    && apt-get update

# 安装基础工具包与 JDK8 环境
RUN apt-get install -y --no-install-recommends \ 
    apt-utils iputils-ping nano openjdk-8-jdk \
    && rm -rf /var/lib/apt/lists/*
    
CMD ["bash"]
